.TH DOVECOT 8 2009/09/26 "dovecot" "System Administration tools and Deamons"
.SH NAME
\fBdovecot\fP \- Secure imap and pop3 server

.SH SYNOPSIS
.B dovecot [\-F] [\-c <config file>] [\-p] [\-n] [\-a] [\-\-version] [\-\-build-options] [\-\-exec-mail <protocol> [<args>]]

.SH FULL PATH
.B /usr/sbin/dovecot

.SH DESCRIPTION
Dovecot is an IMAP server for Linux/UNIX-like systems, written with security 
primarily in mind.  It also contains a small POP3 server.  It supports mail 
in either of maildir or mbox formats.
.SH OPTIONS
.TP
.B \-a
Dump complete configuration and exit
.TP
.B \-\-build-options
Print build options and exit
.TP
.B \-c
Use <config\-file> as path to the configuration instead of default /etc/dovecot.conf
.TP
.B \-\-exec\-mail <protocol> [<args>]
Start protocol from section. If \-\-exec\-mail is used, it must be the last argument on the command line, as <section> is an optional parameter, otherwise if no section is given but
another parameter follows, this parameter is used as section.
.TP
.B \-F
Start dovecot as foreground process (otherwise: start as daemon)
.TP
.B --log-error
Test dovecot's logging capability and exit
.TP
.B \-n
Dump all non-default configuration items and exit
.TP
.B \-p
Ask for private SSL key password
.TP
.B \-\-version
Print version and exit

.SH "SEE ALSO"
.BR dovecotpw(1),
.BR dovecot.conf(5),
.BR /usr/share/doc/dovecot*/wiki/

.SH AUTHOR
.TP
dovecotpw was written by Timo Sirainen <tss@iki.fi>.
